# Base image with Python 3.10
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Copy requirements file
COPY frontend/streamlit/requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy Streamlit app files
COPY frontend/streamlit /app

# Run the Streamlit application
CMD streamlit run app.py --server.port ${PORT:-8501} --server.address 0.0.0.0
