[general]
deploymentMode = true

[browser]
gatherUsageStats = false

[server]
headless = true
port = 8501
enableCORS = true

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
